name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
    SECRET_KEY: django-insecure-bup5*^7o_&&)ci431pj))#g!f$2x%@0cetpbjjxvjpeto!5k&l
    DB_ENGINE: django.db.backends.postgresql_psycopg2
    DB_NAME: db_shop
    DB_USER: postgres
    DB_PASSWORD: 258058
    DB_HOST: localhost
    DB_PORT: 5432
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load environment variables from .env
      run: |
        echo "Loading environment variables..."
        cat .env >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
            cd scr
            python manage.py test
