name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
    SECRET_KEY : 'django-insecure-#p6go@mnl@@c-!tu$zm%+^yq)-k=r8*c@bj!-ep82qy&)#jiu)'
    DB_ENGINE : 'django.db.backends.postgresql_psycopg2'
    DB_NAME : 'places_remember_db'
    DB_USER : 'postgres'
    DB_PASSWORD : '258058'
    DB_HOST : 'localhost'
    DB_PORT : '5432'
    ALLOWED_HOSTS : 'localhost,127.0.0.1'
    SOCIAL_AUTH_VK_OAUTH2_KEY : '51664318'
    SOCIAL_AUTH_VK_OAUTH2_SECRET : 'h31zfABPrR3fcf6aU2da'
    YANDEX_API_KEY : '36365c32-e81e-43f7-9256-26ed505c0379'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load environment variables from .env
      run: |
        echo "Loading environment variables..."
        cat .env >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
            cd scr
            python manage.py test
